package:
  name: openforcefield
  version: 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - networkx
    - lxml
    - openmm
    - packmol
    #- smarty

test:
  requires:
    - nose
    - nose-timer
  imports:
    - openforcefield
  commands:
    - openforcefield

about:
  home: https://github.com/open-forcefield-group/open-forcefield-tools
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
